<header class="cd-header">
	<div class="row">
		<a href="index.php" class="cd-logo"><img src="images/logolight.png" style="width: 50px;" class="img-responsive"alt="Logo"></a>
		<a href="#0" class="cd-3d-nav-trigger">
			Menu
			<span></span>
		</a>
	</div>
	</header>
	<nav class="cd-3d-nav-container">
		<ul class="cd-3d-nav">
			<li class="cd-selected">
				<a href="#0">Home</a>
			</li>

			<li>
				<a href="#0">Products</a>
			</li>

			<li>
				<a href="#0">Services</a>
			</li>

			<li>
				<a href="#0">Customers</a>
			</li>

			<li>
				<a href="#0">Partners</a>
			</li>
			<li>
				<a href="#0">Contact</a>
			</li>
		</ul> <!-- .cd-3d-nav -->

		<span class="cd-marker color-1"></span>	
	</nav>