<!-- Footer Section -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

<footer>
	<div class="container">
		<div class="row">

               <div class="col-md-8 col-sm-6">
                    <div class="wow fadeInUp footer-copyright" data-wow-delay="0.4s">
                         <p>COPYRIGHT &copy; 2018 DATABAR Co.,Ltd.
                         </p>
                    </div>
               </div>

			<!-- <div class="col-md-4 col-sm-6">
				<ul class="wow fadeInUp social-icon" data-wow-delay="0.8s">
                         <li><a href="#" class="fa fa-facebook"></a></li>
                         <li><a href="#" class="fa fa-twitter"></a></li>
                         <li><a href="#" class="fa fa-google-plus"></a></li>
                         <li><a href="#" class="fa fa-dribbble"></a></li>
                         <li><a href="#" class="fa fa-linkedin"></a></li>
                    </ul>
               </div> -->
			
		</div>
	</div>
</footer>

<!-- Back top -->

<a href="#" class="go-top"><i class="fa fa-angle-up" style="width: 30%;"></i></a>

<!-- Modal Contact -->

<div class="modal fade  bd-example-modal-lg" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
     <div class="modal-dialog modal-lg">
      <div class="modal-content modal-popup">
          <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" style="color: #444;">&times;</span></button>
          
          </div>
          <h2 style="color: #000; font-family: 'Open Sans', sans-serif;letter-spacing: 3px;">
               DATABAR COMPANY LIMITED 
          </h2>
          <br>
          <p style="color: #000;letter-spacing: 2px; font-size: 1.2em; padding: 2% 0 3% 0">
               1448/15 Crystal Design Center (CDC), L2 2FL., Room 202. 204. 206.208. 
               Soi Ladprao 87 (Chandra Suk) Praditmanuthum Rd., Klongjan, Bangkapi, Bangkok 10240 ,
               THAILAND.
          </p>
          <div class="row" style="border-bottom: 1px solid #000;">
               <div class="col-md-12">
                    <div class="col-md-4">
                        <p style="margin-bottom : 8%; font-size: 1.2em; color: #000;">T : +66 (0) 2 102-2591</p>
                    </div>
                    <div class="col-md-4">
                         <p style="margin-bottom : 8%; font-size: 1.2em; color: #000;">Fax : +66 (0) 2 102-2590</p>
                    </div>
                    <div class="col-md-4">
                         <a href="mailto:sales@databar.co.th"><p style="margin-bottom : 8%; font-size: 1.2em; color: #000;"> E-mail : sales@databar.co.th</p></a>
                    </div>
                    </div>
          </div>
<div class="row" style="padding: 5% 0 10% 0;">
     <div class="col-md-10 col-md-offset-1">
     <div class="col-md-4">
          <!-- <a href="images/map_CDC.jpg" class="image-popup" data-dismiss="modal"> -->
               <center>
                              <div class="icon">
                                    <a href="print2.php" target="_blank"><i class="fas fa-map-marked-alt fa-5x" style="padding-right: auto; padding-left: auto;"></i>
                                   <p style="color: #000;letter-spacing: 0.5px; font-size: 1em">
                                        Direction
                                   </p>
                                   </a>
                              </div>
               </center>
          
     </div>
     <div class="col-md-4">
          <!-- <a href="images/databarcdc.jpg" class="image-popup" data-dismiss="modal"> -->
               <center>
                         <!-- 
                         <p style="color: #000;letter-spacing: 0.5px;font-size: 1em">
                              CDC Map
                         </p> -->
                         <div class="icon">
                         <a href="print.php" target="_blank"><i class="fas fa-street-view fa-5x"></i>
                              <p style="color: #000;letter-spacing: 0.5px; font-size: 1em">
                                   CDC Map
                              </p>
                        <!--  <span><img src="images/databarcdc.jpg" width="700px" /><br />Simply beautiful.</span></a> -->
                         </a>
                    </div>
               </center>              
                    
     </div>
     <div class="col-md-4">
           <center>
                    <a href="https://www.facebook.com/VAD.databar/" class="icon"  target="_blank"><i class="fab fa-facebook-square fa-5x icon"></i>
                              <p style="color: #000;letter-spacing: 0.5px;font-size: 1em">
                                   VAD.databar
                              </p>
                    </a>
          </center>     
     </div>
     </div>
     <style type="text/css">
          .icon i {
               font-size: 50px;
               top: 20;
               color: #888;
              /* background-color: blue;*/
               padding: 10px;
               z-index: 1;
               /*border: 1px solid #444;*/
               border-radius: 10%;
               transition: all 0.4s ease-in-out;
          }
          .icon i:hover {
               color: #888;
               font-size: 70px;
               /*background-color: #444;*/
          } 
     </style>
     
</div>

<div class="hidden-xs">
<!-- <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15498.40180804764!2d100.617811!3d13.802943!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xbe44151e51909d75!2sDATABAR+Company+Limited!5e0!3m2!1sen!2sus!4v1523197242767" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe> -->
</div>               
     </div>
</div>
</div>
