<!-- Footer Section -->

<footer>
	<div class="container">
		<div class="row">

               <div class="col-md-8 col-sm-6">
                    <div class="wow fadeInUp footer-copyright" data-wow-delay="0.4s">
                         <p>Copyright &copy; 2018 Databar co.,Ltd.
                         </p>
                    </div>
               </div>

			<div class="col-md-4 col-sm-6">
				<ul class="wow fadeInUp social-icon" data-wow-delay="0.8s">
                         <li><a href="#" class="fa fa-facebook"></a></li>
                         <li><a href="#" class="fa fa-twitter"></a></li>
                         <li><a href="#" class="fa fa-google-plus"></a></li>
                         <li><a href="#" class="fa fa-dribbble"></a></li>
                         <li><a href="#" class="fa fa-linkedin"></a></li>
                    </ul>
               </div>
			
		</div>
	</div>
</footer>

<!-- Back top -->

<a href="#" class="go-top"><i class="fa fa-angle-up"></i></a>

<!-- Modal Contact -->

<div class="modal fade  bd-example-modal-lg" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
     <div class="modal-dialog modal-lg">
      <div class="modal-content modal-popup">
          <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
               <h2 class="modal-title">Contact Info</h2>
               <hr>
          </div>
          <p style="color: #FFF; font-family: 'Signika', sans-serif;">
               DATABAR Company Limited 
          </p>
          <p style="color: #FFF;">
               1448/15 Crystal Design Center (CDC), L2 2FL., <br>
               Room 202. 204. 206.208. <br>
               Soi Ladprao 87 (Chandra Suk) Praditmanuthum Rd., <br>
               Klongjan, Bangkapi, Bangkok 10240, <br>
               THAILAND 
          </p>
          <hr>
            
          <p style="color: #FFF;">
          Telphone : +66 2 102 2591 <a href="tel:+66 2 102 2591"><font color="white">(click hear to call)</font></a><br>
          E-mail : sales@databar.co.th    
          </p>

<div class="row">
     <div class="col-md-6">
          <a href="images/map_CDC.jpg" class="image-popup1" data-dismiss="modal">
               <img src="images/map_CDC.jpg" class="img-responsive" alt="map">
          </a>            
     </div>
     <div class="col-md-6">
          <a href="images/databarcdc.jpg" class="image-popup1" data-dismiss="modal">
                <img src="images/databarcdc.jpg" class="img-responsive" alt="map">
          </a>          
     </div>
</div>    
<div class="hidden-xs">
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15498.40180804764!2d100.617811!3d13.802943!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xbe44151e51909d75!2sDATABAR+Company+Limited!5e0!3m2!1sen!2sus!4v1523197242767" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>               
     </div>
</div>
